FROM ruby:3.1.4

RUN apt-get update -qq && apt-get install -y build-essential ca-certificates gnupg nodejs vim

RUN mkdir /backend
WORKDIR /backend

COPY Gemfile ./
COPY Gemfile.lock ./

RUN bundle install

COPY . /myapp

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]


EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
